enable_language(OBJC)
include(CheckOBJCSourceCompiles)
foreach(framework CoreFoundation CoreMedia CoreVideo CoreAudio AudioToolbox VideoToolbox AVFoundation Foundation Security CoreGraphics ApplicationServices IOKit QuartzCore)
  find_library(FF_FRAMEWORK_${framework} ${framework} REQUIRED)
  list(APPEND FF_EXTERNAL_LIBS "-framework ${framework}")
  string(TOUPPER "${framework}" macro)
  ff_fact(HAVE_${macro} 1)
endforeach()
set(CMAKE_REQUIRED_LIBRARIES ${FF_EXTERNAL_LIBS})
ff_fact(CONFIG_AUDIOTOOLBOX 1)
ff_fact(CONFIG_VIDEOTOOLBOX 1)
ff_fact(CONFIG_AVFOUNDATION 1)
ff_probe(CONFIG_SECURETRANSPORT "#include <Security/SecureTransport.h>\nint main(void) { return SSLCreateContext(0, kSSLClientSide, kSSLStreamType) == 0; }")
foreach(symbol VTDecompressionSessionDecodeFrame VTCompressionSessionPrepareToEncodeFrames)
  ff_symbol(${symbol} "VideoToolbox/VideoToolbox.h")
endforeach()
check_objc_source_compiles("#import <AVFoundation/AVFoundation.h>\nint main(void) { AVCaptureSession *s = [[AVCaptureSession alloc] init]; [s release]; return 0; }" FF_AVCAPTURESESSION)
ff_fact(AVCaptureSession "${FF_AVCAPTURESESSION}")
ff_probe(AudioObjectPropertyAddress "#include <CoreAudio/CoreAudio.h>\nint main(void) { return sizeof(AudioObjectPropertyAddress); }")
foreach(symbol kCMVideoCodecType_HEVC kCMVideoCodecType_HEVCWithAlpha kCMVideoCodecType_VP9 kCMVideoCodecType_AV1)
  ff_symbol(${symbol} "CoreMedia/CoreMedia.h")
endforeach()
foreach(symbol kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange kCVPixelFormatType_422YpCbCr8BiPlanarVideoRange kCVPixelFormatType_422YpCbCr10BiPlanarVideoRange kCVPixelFormatType_422YpCbCr16BiPlanarVideoRange kCVPixelFormatType_444YpCbCr8BiPlanarVideoRange kCVPixelFormatType_444YpCbCr10BiPlanarVideoRange kCVPixelFormatType_444YpCbCr16BiPlanarVideoRange kCVPixelFormatType_422YpCbCr8_yuvs kCVImageBufferTransferFunction_SMPTE_ST_2084_PQ kCVImageBufferTransferFunction_ITU_R_2100_HLG kCVImageBufferTransferFunction_Linear kCVImageBufferYCbCrMatrix_ITU_R_2020 kCVImageBufferColorPrimaries_ITU_R_2020 kCVImageBufferTransferFunction_ITU_R_2020 kCVImageBufferTransferFunction_SMPTE_ST_428_1)
  ff_symbol(${symbol} "CoreVideo/CoreVideo.h")
endforeach()
ff_symbol(kVTQPModulationLevel_Default "VideoToolbox/VideoToolbox.h")
set(CMAKE_REQUIRED_LIBRARIES "")
