# MSVC has no GNU inline assembler. NASM provides the optimized implementations
# for both MSVC and clang-cl, without relying on a Unix assembler or shell.
ff_fact(HAVE_INLINE_ASM 0)
if(FF_ARCH STREQUAL "x86" AND NOT FFMPEG_ASM STREQUAL "OFF")
  find_program(FF_NASM nasm HINTS "${PROJECT_SOURCE_DIR}/.tools/bin")
  if(FF_NASM)
    set(CMAKE_ASM_NASM_COMPILER "${FF_NASM}")
    if(WIN32)
      set(CMAKE_ASM_NASM_OBJECT_FORMAT win64)
    elseif(APPLE)
      set(CMAKE_ASM_NASM_OBJECT_FORMAT macho64)
    else()
      set(CMAKE_ASM_NASM_OBJECT_FORMAT elf64)
    endif()
    enable_language(ASM_NASM)
    ff_fact(HAVE_X86ASM 1)
  elseif(FFMPEG_ASM STREQUAL "ON")
    message(FATAL_ERROR "FFMPEG_ASM=ON requires NASM. Run tools/bootstrap.py or install nasm.")
  else()
    message(STATUS "NASM not found: using portable C implementations")
  endif()
endif()
if(FF_ARCH STREQUAL "aarch64" AND NOT MSVC AND NOT FFMPEG_ASM STREQUAL "OFF")
  enable_language(ASM)
  ff_fact(HAVE_ARMV8 1)
  ff_fact(HAVE_NEON 1)
  ff_fact(HAVE_SIMD_ALIGN_16 1)
  ff_probe(HAVE_INTRINSICS_NEON "#include <arm_neon.h>\nint main(void) { return vgetq_lane_s32(vdupq_n_s32(0), 0); }")
  ff_probe(HAVE_AS_FUNC "__asm__(\".func test\\n.endfunc\");\nint main(void) { return 0; }")
  ff_probe(HAVE_AS_ARCH_DIRECTIVE "__asm__(\".arch armv8-a\");\nint main(void) { return 0; }")
  foreach(pair "arm_crc|crc|crc32x w0, w0, x0" "dotprod|dotprod|udot v0.4s, v0.16b, v0.16b" "i8mm|i8mm|usdot v0.4s, v0.16b, v0.16b" "pmull|aes|pmull v0.1q, v0.1d, v0.1d" "eor3|sha3|eor3 v0.16b, v0.16b, v0.16b, v0.16b" "sve|sve|ptrue p0.b" "sve2|sve2|usdot z0.s, z0.b, z0.b" "sme|sme|smstart" "sme2|sme2|zero {zt0}")
    string(REPLACE "|" ";" parts "${pair}")
    list(GET parts 0 feature)
    list(GET parts 1 extension)
    list(GET parts 2 instruction)
    string(TOUPPER "${feature}" macro)
    string(TOUPPER "${extension}" directive)
    ff_probe(HAVE_${macro} "__asm__(\".arch armv8-a\\n.arch_extension ${extension}\\n${instruction}\\n.arch armv8-a\");\nint main(void) { return 0; }")
    ff_fact(HAVE_AS_ARCHEXT_${directive}_DIRECTIVE "${HAVE_${macro}}")
  endforeach()
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  ff_fact(HAVE_SECTION_DATA_REL_RO 1)
endif()
