find_package(Threads REQUIRED)
set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_THREAD_LIBS_INIT} m ${CMAKE_DL_LIBS})
ff_fact(HAVE_PTHREADS "${CMAKE_USE_PTHREADS_INIT}")
ff_fact(HAVE_THREADS 1)
ff_fact(libm 1)
ff_fact(libdl "${CMAKE_DL_LIBS}")
set(net_headers "#include <sys/types.h>\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <netdb.h>\n#include <poll.h>\n")
foreach(header arpa/inet.h dirent.h malloc.h poll.h pthread_np.h sys/param.h sys/resource.h sys/select.h sys/time.h sys/un.h termios.h unistd.h)
  string(TOUPPER "${header}" key)
  string(REPLACE "/" "_" key "${key}")
  string(REPLACE "." "_" key "${key}")
  check_include_file("${header}" FF_HEADER_${key})
  ff_fact(HAVE_${key} "${FF_HEADER_${key}}")
endforeach()
foreach(symbol access gethostname getopt isatty lstat readlink sysconf usleep)
  ff_symbol(${symbol} "unistd.h")
endforeach()
foreach(symbol clock_gettime gmtime_r localtime_r nanosleep)
  ff_symbol(${symbol} "time.h")
endforeach()
foreach(symbol aligned_alloc arc4random_buf mkstemp posix_memalign)
  ff_symbol(${symbol} "stdlib.h")
endforeach()
ff_symbol(gettimeofday "sys/time.h")
ff_symbol(getaddrinfo "sys/types.h;sys/socket.h;netdb.h")
ff_symbol(mmap "sys/mman.h")
ff_symbol(mprotect "sys/mman.h")
ff_symbol(fcntl "fcntl.h")
ff_symbol(ioctl "sys/ioctl.h")
ff_symbol(getrusage "sys/resource.h")
ff_symbol(setrlimit "sys/resource.h")
ff_symbol(sigaction "signal.h")
ff_symbol(siglongjmp "setjmp.h")
ff_symbol(pthread_cancel "pthread.h")
ff_symbol(pthread_setname_np "pthread.h")
ff_symbol(pthread_setaffinity_np "pthread.h")
ff_symbol(sched_getaffinity "sched.h")
ff_symbol(getauxval "sys/auxv.h")
ff_symbol(prctl "sys/prctl.h")
ff_symbol(sem_timedwait "semaphore.h")
ff_symbol(sysctl "sys/types.h;sys/sysctl.h")
ff_symbol(sysctlbyname "sys/types.h;sys/sysctl.h")
ff_symbol(gethrtime "sys/time.h")
ff_symbol(poll "poll.h")
ff_symbol(strtok_r "string.h")
ff_symbol(glob "glob.h")
ff_symbol(sched_yield "sched.h")
ff_symbol(getrandom "sys/random.h")
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  foreach(header linux/videodev2.h linux/fb.h sys/soundcard.h)
    string(TOUPPER "${header}" key)
    string(REPLACE "/" "_" key "${key}")
    string(REPLACE "." "_" key "${key}")
    check_include_file("${header}" FF_HEADER_${key})
    ff_fact(HAVE_${key} "${FF_HEADER_${key}}")
  endforeach()
  ff_probe(CONFIG_V4L2_M2M "#include <linux/videodev2.h>\nint main(void) { return V4L2_CAP_VIDEO_M2M_MPLANE | V4L2_CAP_VIDEO_M2M | V4L2_BUF_FLAG_LAST; }")
  foreach(codec h263 h264 hevc mpeg1 mpeg2 mpeg4 vp8 vp9 vc1)
    string(TOUPPER "${codec}" format)
    if(codec STREQUAL "vc1")
      set(format VC1_ANNEX_G)
    endif()
    ff_probe(${codec}_v4l2_m2m "#include <linux/videodev2.h>\nint main(void) { return V4L2_PIX_FMT_${format}; }")
  endforeach()
  ff_probe(HAVE_STRUCT_V4L2_FRMIVALENUM_DISCRETE "#include <linux/videodev2.h>\nint main(void) { struct v4l2_frmivalenum v; return sizeof(v.discrete); }")
endif()
