set(CMAKE_REQUIRED_LIBRARIES ws2_32 bcrypt ole32 user32 psapi shell32 secur32)
ff_fact(HAVE_DOS_PATHS 1)
ff_fact(HAVE_LIBC_MSVCRT 1)
ff_fact(HAVE_W32THREADS 1)
ff_fact(HAVE_THREADS 1)
ff_fact(atomics_native 1)
ff_fact(atomics_win32 1)
foreach(lib bcrypt ole32 user32 psapi shell32 secur32)
  ff_fact(${lib} 1)
endforeach()
foreach(header windows.h winsock2.h direct.h io.h malloc.h)
  string(TOUPPER "${header}" key)
  string(REPLACE "." "_" key "${key}")
  check_include_file("${header}" FF_HEADER_${key})
  ff_fact(HAVE_${key} "${FF_HEADER_${key}}")
endforeach()
foreach(symbol GetModuleHandle GetProcessAffinityMask GetProcessTimes GetStdHandle GetSystemTimeAsFileTime MapViewOfFile PeekNamedPipe SetConsoleTextAttribute SetConsoleCtrlHandler SetDllDirectory Sleep VirtualAlloc MemoryBarrier LoadLibrary)
  ff_symbol(${symbol} "windows.h")
endforeach()
ff_symbol(GetProcessMemoryInfo "windows.h;psapi.h")
ff_symbol(CommandLineToArgvW "windows.h;shellapi.h")
ff_symbol(closesocket "winsock2.h")
ff_symbol(getaddrinfo "winsock2.h;ws2tcpip.h")
foreach(symbol access isatty setmode)
  ff_symbol(${symbol} "io.h")
endforeach()
ff_symbol(kbhit "conio.h")
ff_probe(HAVE_ALIGNED_MALLOC "#include <malloc.h>\nint main(void) { void *p = _aligned_malloc(16, 16); _aligned_free(p); return 0; }")
set(net_headers "#include <winsock2.h>\n#include <ws2tcpip.h>\n")
ff_probe(CONFIG_SCHANNEL "#define SECURITY_WIN32\n#include <windows.h>\n#include <security.h>\n#include <schannel.h>\nint main(void) { return InitSecurityInterfaceW() == 0; }")
ff_probe(HAVE_SECPKGCONTEXT_KEYINGMATERIALINFO "#define SECURITY_WIN32\n#include <windows.h>\n#include <security.h>\n#include <schannel.h>\nint main(void) { return sizeof(SecPkgContext_KeyingMaterialInfo) == 0; }")
ff_probe(HAVE_DXVA_H "#include <windows.h>\n#include <d3d9.h>\n#include <dxva.h>\nint main(void) { return 0; }")
ff_probe(dxva2api_h "#include <windows.h>\n#include <d3d9.h>\n#include <dxva2api.h>\nint main(void) { return 0; }")
foreach(type DXVA2_ConfigPictureDecode)
  ff_probe(${type} "#include <windows.h>\n#include <d3d9.h>\n#include <dxva2api.h>\nint main(void) { return sizeof(${type}) == 0; }")
endforeach()
foreach(type ID3D11VideoDecoder ID3D11VideoContext)
  ff_probe(${type} "#include <windows.h>\n#include <d3d11.h>\nint main(void) { ${type} *p = 0; return p != 0; }")
endforeach()
foreach(type ID3D12Device ID3D12VideoDecoder ID3D12VideoEncoder ID3D12VideoProcessor ID3D12VideoMotionEstimator)
  ff_probe(${type} "#include <windows.h>\n#include <d3d12.h>\n#include <d3d12video.h>\nint main(void) { ${type} *p = 0; return p != 0; }")
endforeach()
foreach(type DXVA_PicParams_AV1 DXVA_PicParams_HEVC DXVA_PicParams_VP9)
  ff_probe(${type} "#include <windows.h>\n#include <d3d9.h>\n#include <dxva.h>\nint main(void) { return sizeof(${type}) == 0; }")
endforeach()
if(HAVE_DXVA_H AND ID3D11VideoDecoder AND ID3D11VideoContext)
  ff_fact(CONFIG_D3D11VA 1)
endif()
if(HAVE_DXVA_H AND ID3D12Device AND ID3D12VideoDecoder)
  ff_fact(CONFIG_D3D12VA 1)
endif()
if(dxva2api_h AND DXVA2_ConfigPictureDecode)
  ff_fact(CONFIG_DXVA2 1)
endif()
ff_probe(d3d12_encoder_feature "#include <windows.h>\n#include <d3d12video.h>\nint main(void) { D3D12_FEATURE_VIDEO f = D3D12_FEATURE_VIDEO_ENCODER_CODEC; D3D12_FEATURE_DATA_VIDEO_ENCODER_RESOURCE_REQUIREMENTS r; return sizeof(r) + f == 0; }")
ff_probe(d3d12va_av1_headers "#include <windows.h>\n#include <d3d12video.h>\nint main(void) { D3D12_VIDEO_ENCODER_CODEC c = D3D12_VIDEO_ENCODER_CODEC_AV1; return c == 0; }")
foreach(pair "D3D12_INTRA_REFRESH|D3D12_FEATURE_DATA_VIDEO_ENCODER_INTRA_REFRESH_MODE" "D3D12_MOTION_ESTIMATOR|D3D12_FEATURE_DATA_VIDEO_MOTION_ESTIMATOR" "D3D12_VIDEO_PROCESS_REFERENCE_INFO|D3D12_FEATURE_DATA_VIDEO_PROCESS_REFERENCE_INFO")
  string(REPLACE "|" ";" pair "${pair}")
  list(GET pair 0 key)
  list(GET pair 1 type)
  ff_probe(CONFIG_${key} "#include <windows.h>\n#include <d3d12video.h>\nint main(void) { return sizeof(${type}) == 0; }")
endforeach()
ff_probe(CONFIG_D3D12VA_ME_PRECISION_EIGHTH_PIXEL "#include <windows.h>\n#include <d3d12video.h>\nint main(void) { return D3D12_VIDEO_ENCODER_MOTION_ESTIMATION_PRECISION_MODE_EIGHTH_PIXEL == 0; }")
ff_probe(IDXGIOutput1 "#include <windows.h>\n#include <dxgi1_2.h>\nint main(void) { IDXGIOutput1 *p = 0; return p != 0; }")
ff_probe(DXGI_OUTDUPL_FRAME_INFO "#include <windows.h>\n#include <dxgi1_2.h>\nint main(void) { return sizeof(DXGI_OUTDUPL_FRAME_INFO) == 0; }")
ff_probe(HAVE_IDXGIOUTPUT5 "#include <windows.h>\n#include <dxgi1_5.h>\nint main(void) { IDXGIOutput5 *p = 0; return p != 0; }")
ff_probe(HAVE_DPI_AWARENESS_CONTEXT "#include <windows.h>\nint main(void) { return sizeof(DPI_AWARENESS_CONTEXT) == 0; }")
ff_probe(IBaseFilter "#include <dshow.h>\nint main(void) { IBaseFilter *p = 0; return p != 0; }")
list(APPEND CMAKE_REQUIRED_LIBRARIES gdi32 vfw32 mfplat mfuuid)
ff_probe(CreateDIBSection "#include <windows.h>\nint main(void) { return CreateDIBSection(0, 0, 0, 0, 0, 0) != 0; }")
ff_probe(vfw32 "#include <windows.h>\n#include <vfw.h>\nint main(void) { return capCreateCaptureWindowA(0, 0, 0, 0, 0, 0, 0, 0) != 0; }")
ff_probe(vfwcap_defines "#include <windows.h>\n#include <vfw.h>\n_Static_assert(WM_CAP_DRIVER_CONNECT > WM_USER, \"VFW API\");\nint main(void) { return 0; }")
ff_probe(mftransform_h "#include <windows.h>\n#include <mftransform.h>\nint main(void) { return 0; }")
ff_probe(MFCreateAlignedMemoryBuffer "#include <windows.h>\n#include <mfapi.h>\nint main(void) { return MFCreateAlignedMemoryBuffer(0, 0, 0); }")
if(mftransform_h AND MFCreateAlignedMemoryBuffer)
  ff_fact(CONFIG_MEDIAFOUNDATION 1)
endif()
set(winrt_prefix "#define COBJMACROS\n#define WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION 0x130000\n#include <windows.h>\n")
ff_probe(IGraphicsCaptureItemInterop "${winrt_prefix}#include <windows.graphics.capture.interop.h>\nint main(void) { IGraphicsCaptureItemInterop *p = 0; return p != 0; }")
ff_probe(__x_ABI_CWindows_CGraphics_CCapture_CIGraphicsCaptureSession3 "${winrt_prefix}#include <windows.graphics.capture.h>\nint main(void) { __x_ABI_CWindows_CGraphics_CCapture_CIGraphicsCaptureSession3 *p = 0; return p != 0; }")
ff_probe(HAVE___X_ABI_CWINDOWS_CGRAPHICS_CCAPTURE_CIGRAPHICSCAPTURESESSION5 "${winrt_prefix}#include <windows.graphics.capture.h>\nint main(void) { __x_ABI_CWindows_CGraphics_CCapture_CIGraphicsCaptureSession5 *p = 0; return p != 0; }")
ff_probe(HAVE_IDIRECT3DDXGIINTERFACEACCESS "${winrt_prefix}#include <windows.graphics.directx.direct3d11.interop.h>\nint main(void) { IDirect3DDxgiInterfaceAccess *p = 0; return p != 0; }")
