if(FFMPEG_CACHE AND NOT CMAKE_C_COMPILER_LAUNCHER)
  find_program(FFMPEG_COMPILER_CACHE sccache HINTS "${PROJECT_SOURCE_DIR}/.tools/bin")
  if(FFMPEG_COMPILER_CACHE)
    set(CMAKE_C_COMPILER_LAUNCHER "${FFMPEG_COMPILER_CACHE}")
    set(CMAKE_CXX_COMPILER_LAUNCHER "${FFMPEG_COMPILER_CACHE}")
    message(STATUS "Compiler cache: ${FFMPEG_COMPILER_CACHE}")
  else()
    message(STATUS "Compiler cache not found; parallel incremental builds remain enabled")
  endif()
endif()
if(FFMPEG_LTO)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT ipo_ok OUTPUT ipo_error LANGUAGES C)
  if(NOT ipo_ok)
    message(FATAL_ERROR "LTO is unavailable: ${ipo_error}")
  endif()
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
endif()
set_property(GLOBAL APPEND PROPERTY JOB_POOLS "ffmpeg_link=${FFMPEG_LINK_JOBS}")
set(CMAKE_JOB_POOL_LINK ffmpeg_link)
if(FFMPEG_COMPILE_JOBS)
  set_property(GLOBAL APPEND PROPERTY JOB_POOLS "ffmpeg_compile=${FFMPEG_COMPILE_JOBS}")
  set(CMAKE_JOB_POOL_COMPILE ffmpeg_compile)
endif()
