include(${CMAKE_CURRENT_LIST_DIR}/Json.cmake)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${FFMPEG_ROOT}/tools/dependencies.py" "${FFMPEG_ROOT}/tools/dependencies.json")
find_package(Python3 3.10 REQUIRED COMPONENTS Interpreter)
if(FFMPEG_DEPENDENCIES AND NOT FFMPEG_DEPENDENCY_PREFIX)
  file(MAKE_DIRECTORY "${FFMPEG_ROOT}/.cache")
  file(LOCK "${FFMPEG_ROOT}/.cache/dependencies.lock" GUARD PROCESS TIMEOUT 3600)
  set(context "{}")
  file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" driver_hash)
  file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/DependencyProject.cmake" project_hash)
  ff_json_string(value "${FF_TOOLCHAIN_KEY};${driver_hash};${project_hash}")
  string(JSON context SET "${context}" identity "${value}")
  ff_json_string(value "${CMAKE_COMMAND}")
  string(JSON context SET "${context}" cmake "${value}")
  ff_json_string(value "${CMAKE_BUILD_TYPE}")
  string(JSON context SET "${context}" configuration "${value}")
  string(JSON context SET "${context}" arguments "[]")
  set(CMAKE_PROJECT_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/DependencyProject.cmake")
  set(CMAKE_POLICY_DEFAULT_CMP0141 NEW)
  set(CMAKE_POLICY_DEFAULT_CMP0091 NEW)
  set(index 0)
  foreach(var CMAKE_PROJECT_INCLUDE CMAKE_POLICY_DEFAULT_CMP0141 CMAKE_POLICY_DEFAULT_CMP0091 CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_TOOLCHAIN_FILE CMAKE_BUILD_TYPE
      CMAKE_C_COMPILER_TARGET CMAKE_CXX_COMPILER_TARGET CMAKE_SYSROOT
      CMAKE_OSX_SYSROOT CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET
      CMAKE_C_FLAGS CMAKE_CXX_FLAGS CMAKE_C_FLAGS_RELEASE CMAKE_CXX_FLAGS_RELEASE
      CMAKE_C_FLAGS_DEBUG CMAKE_CXX_FLAGS_DEBUG CMAKE_C_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_RELWITHDEBINFO
      CMAKE_C_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_EXE_LINKER_FLAGS CMAKE_MSVC_RUNTIME_LIBRARY
      CMAKE_C_COMPILER_LAUNCHER CMAKE_CXX_COMPILER_LAUNCHER)
    if(DEFINED ${var} AND NOT "${${var}}" STREQUAL "")
      ff_json_string(value "-D${var}=${${var}}")
      string(JSON context SET "${context}" arguments ${index} "${value}")
      math(EXPR index "${index} + 1")
    endif()
  endforeach()
  file(CONFIGURE OUTPUT "${PROJECT_BINARY_DIR}/dependency-context.json" CONTENT "${context}" @ONLY)
  set(options "")
  if(FFMPEG_GPL)
    list(APPEND options --gpl)
  endif()
  if(FFMPEG_COMPILE_JOBS)
    list(APPEND options --jobs "${FFMPEG_COMPILE_JOBS}")
  endif()
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${FFMPEG_ROOT}/tools/dependencies.py"
    --selection "${FFMPEG_DEPENDENCIES}" --context "${PROJECT_BINARY_DIR}/dependency-context.json"
    --output "${PROJECT_BINARY_DIR}/dependency-prefix.txt" ${options}
    COMMAND_ERROR_IS_FATAL ANY)
  file(READ "${PROJECT_BINARY_DIR}/dependency-prefix.txt" FFMPEG_DEPENDENCY_PREFIX)
  file(LOCK "${FFMPEG_ROOT}/.cache/dependencies.lock" RELEASE)
endif()
if(FFMPEG_DEPENDENCY_PREFIX)
  list(PREPEND CMAKE_PREFIX_PATH "${FFMPEG_DEPENDENCY_PREFIX}")
endif()
if((FFMPEG_DEPENDENCY_PREFIX OR DEFINED FF_LAST_DEPENDENCY_PREFIX) AND NOT FF_LAST_DEPENDENCY_PREFIX STREQUAL FFMPEG_DEPENDENCY_PREFIX)
  get_cmake_property(variables CACHE_VARIABLES)
  foreach(var IN LISTS variables)
    foreach(prefix ZLIB_ OPUS_ Opus_ OGG_ Ogg_ VORBIS_ Vorbis_ WEBP_ WebP_ FREETYPE_ Freetype_ harfbuzz_ LIBLZMA_ SDL2_ FF_aom_ FF_x265_)
      string(FIND "${var}" "${prefix}" position)
      if(position EQUAL 0)
        unset(${var} CACHE)
      endif()
    endforeach()
  endforeach()
endif()
set(FF_LAST_DEPENDENCY_PREFIX "${FFMPEG_DEPENDENCY_PREFIX}" CACHE INTERNAL "External package search prefix" FORCE)
