set(FF_EXTERNAL_LIBS "")
find_package(ZLIB QUIET)
if(NOT ZLIB_FOUND AND FFMPEG_FETCH_ZLIB)
  include(FetchContent)
  set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
  set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
  set(ZLIB_INSTALL ON CACHE BOOL "" FORCE)
  FetchContent_Declare(zlib GIT_REPOSITORY https://github.com/madler/zlib.git
    GIT_TAG da607da739fa6047df13e66a2af6b8bec7c2a498) # zlib 1.3.2
  FetchContent_MakeAvailable(zlib)
  set(FF_ZLIB_TARGET zlibstatic)
  set(ZLIB_FOUND TRUE)
  set(FF_BUNDLED_ZLIB TRUE)
elseif(ZLIB_FOUND)
  set(FF_ZLIB_TARGET ZLIB::ZLIB)
endif()
if(ZLIB_FOUND)
  if(FF_BUNDLED_ZLIB)
    list(APPEND FF_EXTERNAL_LIBS "$<BUILD_INTERFACE:${FF_ZLIB_TARGET}>" "$<INSTALL_INTERFACE:ZLIB::ZLIBSTATIC>")
  else()
    list(APPEND FF_EXTERNAL_LIBS "${FF_ZLIB_TARGET}")
  endif()
endif()
ff_fact(CONFIG_ZLIB "${ZLIB_FOUND}")
find_package(BZip2 QUIET)
ff_fact(CONFIG_BZLIB "${BZIP2_FOUND}")
if(BZIP2_FOUND)
  list(APPEND FF_EXTERNAL_LIBS BZip2::BZip2)
endif()
find_package(LibLZMA QUIET)
ff_fact(CONFIG_LZMA "${LIBLZMA_FOUND}")
if(LIBLZMA_FOUND)
  list(APPEND FF_EXTERNAL_LIBS LibLZMA::LibLZMA)
endif()
find_package(Iconv QUIET)
ff_fact(CONFIG_ICONV "${Iconv_FOUND}")
if(Iconv_FOUND)
  list(APPEND FF_EXTERNAL_LIBS Iconv::Iconv)
endif()
find_package(SDL2 CONFIG QUIET)
ff_fact(CONFIG_SDL2 "${SDL2_FOUND}")
if(NOT WIN32)
  find_package(OpenSSL QUIET)
  # OpenSSL 3 is compatible with FFmpeg only when the corresponding license
  # option is enabled, as in upstream configure.
  if(OpenSSL_FOUND AND FFMPEG_VERSION3)
    ff_fact(CONFIG_OPENSSL 1)
    list(APPEND FF_EXTERNAL_LIBS OpenSSL::SSL OpenSSL::Crypto)
  endif()
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  find_package(ALSA QUIET)
  ff_fact(CONFIG_ALSA "${ALSA_FOUND}")
  if(ALSA_FOUND)
    list(APPEND FF_EXTERNAL_LIBS ALSA::ALSA)
  endif()
elseif(APPLE)
  include(${CMAKE_CURRENT_LIST_DIR}/platform/Apple.cmake)
endif()
