include(${CMAKE_CURRENT_LIST_DIR}/DependencyBuild.cmake)
set(FF_EXTERNAL_LIBS "")
if(EXISTS "${FFMPEG_DEPENDENCY_PREFIX}/lib/cmake/ZLIB/ZLIBConfig.cmake")
  find_package(ZLIB REQUIRED CONFIG COMPONENTS static)
  set(FF_ZLIB_TARGET ZLIB::ZLIBSTATIC)
  set(FF_CONFIG_ZLIB_STATIC TRUE)
  if(NOT TARGET ZLIB::ZLIB)
    add_library(ZLIB::ZLIB ALIAS ZLIB::ZLIBSTATIC)
  endif()
else()
  find_package(ZLIB QUIET)
endif()
if(NOT ZLIB_FOUND AND FFMPEG_FETCH_ZLIB)
  include(FetchContent)
  set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
  set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
  set(ZLIB_INSTALL ON CACHE BOOL "" FORCE)
  FetchContent_Declare(zlib GIT_REPOSITORY https://github.com/madler/zlib.git
    GIT_TAG da607da739fa6047df13e66a2af6b8bec7c2a498) # zlib 1.3.2
  FetchContent_MakeAvailable(zlib)
  set(FF_ZLIB_TARGET zlibstatic)
  set(ZLIB_FOUND TRUE)
  set(FF_BUNDLED_ZLIB TRUE)
  set(FF_CONFIG_ZLIB_STATIC TRUE)
elseif(ZLIB_FOUND AND NOT FF_CONFIG_ZLIB_STATIC)
  set(FF_ZLIB_TARGET ZLIB::ZLIB)
endif()
if(ZLIB_FOUND)
  if(FF_BUNDLED_ZLIB)
    list(APPEND FF_EXTERNAL_LIBS "$<BUILD_INTERFACE:${FF_ZLIB_TARGET}>" "$<INSTALL_INTERFACE:ZLIB::ZLIBSTATIC>")
  else()
    list(APPEND FF_EXTERNAL_LIBS "${FF_ZLIB_TARGET}")
  endif()
endif()
ff_fact(CONFIG_ZLIB "${ZLIB_FOUND}")
find_package(BZip2 QUIET)
ff_fact(CONFIG_BZLIB "${BZIP2_FOUND}")
if(BZIP2_FOUND)
  list(APPEND FF_EXTERNAL_LIBS BZip2::BZip2)
endif()
find_package(LibLZMA QUIET)
ff_fact(CONFIG_LZMA "${LIBLZMA_FOUND}")
if(LIBLZMA_FOUND)
  if(WIN32 AND FFMPEG_DEPENDENCY_PREFIX)
    set_property(TARGET LibLZMA::LibLZMA APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS LZMA_API_STATIC)
  endif()
  list(APPEND FF_EXTERNAL_LIBS LibLZMA::LibLZMA)
endif()
find_package(Iconv QUIET)
ff_fact(CONFIG_ICONV "${Iconv_FOUND}")
if(Iconv_FOUND)
  list(APPEND FF_EXTERNAL_LIBS Iconv::Iconv)
endif()
find_package(SDL2 CONFIG QUIET)
ff_fact(CONFIG_SDL2 "${SDL2_FOUND}")
if(NOT WIN32)
  find_package(OpenSSL QUIET)
  # OpenSSL 3 is compatible with FFmpeg only when the corresponding license
  # option is enabled, as in upstream configure.
  if(OpenSSL_FOUND AND FFMPEG_VERSION3)
    ff_fact(CONFIG_OPENSSL 1)
    list(APPEND FF_EXTERNAL_LIBS OpenSSL::SSL OpenSSL::Crypto)
  endif()
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  find_package(ALSA QUIET)
  ff_fact(CONFIG_ALSA "${ALSA_FOUND}")
  if(ALSA_FOUND)
    list(APPEND FF_EXTERNAL_LIBS ALSA::ALSA)
  endif()
elseif(APPLE)
  include(${CMAKE_CURRENT_LIST_DIR}/platform/Apple.cmake)
endif()

set(FF_EXTERNAL_GPL "${FFMPEG_GPL}")
set(FF_EXTERNAL_PKGCONFIG "${FFMPEG_PKG_CONFIG_LIBRARIES}")
if(libx264 IN_LIST FF_EXTERNAL_PKGCONFIG AND NOT FFMPEG_GPL)
  message(FATAL_ERROR "libx264 requires FFMPEG_GPL=ON")
endif()
if(libfdk_aac IN_LIST FF_EXTERNAL_PKGCONFIG)
  message(FATAL_ERROR "libfdk_aac requires a nonfree FFmpeg build, which this distributable build does not enable")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/ExternalPackages.cmake)
set(FF_REQUIRED_PACKAGES "")
foreach(row "Opus|Opus::opus|libopus" "Vorbis|Vorbis::vorbis|libvorbis"
    "Vorbis|Vorbis::vorbisenc|libvorbisenc" "WebP|WebP::webp|libwebp"
    "WebP|WebP::libwebpmux|libwebp_anim_encoder" "Freetype|Freetype::Freetype|libfreetype"
    "harfbuzz|harfbuzz::harfbuzz|libharfbuzz" "aom|FFmpegExternal::aom|libaom" "x265|FFmpegExternal::x265|libx265")
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 0 package)
  list(GET fields 1 target)
  list(GET fields 2 feature)
  if(TARGET ${target})
    string(TOUPPER "${feature}" macro)
    ff_fact(CONFIG_${macro} 1)
    list(APPEND FF_EXTERNAL_LIBS ${target})
    list(APPEND FF_REQUIRED_PACKAGES ${package})
  endif()
endforeach()
list(REMOVE_DUPLICATES FF_REQUIRED_PACKAGES)
foreach(name IN LISTS FF_EXTERNAL_PKGCONFIG)
  if(NOT TARGET PkgConfig::FF_PKG_${name})
    message(FATAL_ERROR "Unsupported pkg-config library: ${name}")
  endif()
  string(TOUPPER "${name}" macro)
  ff_fact(CONFIG_${macro} 1)
  if(name STREQUAL "libwebpmux")
    ff_fact(CONFIG_LIBWEBP_ANIM_ENCODER 1)
  endif()
  list(APPEND FF_EXTERNAL_LIBS PkgConfig::FF_PKG_${name})
endforeach()
message(STATUS "External CMake packages: ${FF_REQUIRED_PACKAGES}")
