# Shared by the build and installed FFmpegConfig.cmake. Keep imported targets
# relocatable by finding each package again at its new installation prefix.
function(ff_external_package package)
  set(required "")
  if(package IN_LIST FF_REQUIRED_PACKAGES)
    set(required REQUIRED)
  endif()
  find_package(${package} ${required} QUIET ${ARGN})
  set(${package}_FOUND "${${package}_FOUND}" PARENT_SCOPE)
endfunction()

ff_external_package(Opus CONFIG)
ff_external_package(Vorbis CONFIG)
ff_external_package(WebP CONFIG)
ff_external_package(Freetype)
ff_external_package(harfbuzz CONFIG)
if(TARGET Freetype::Freetype AND TARGET ZLIB::ZLIB)
  set_property(TARGET Freetype::Freetype APPEND PROPERTY INTERFACE_LINK_LIBRARIES ZLIB::ZLIB)
endif()
if(TARGET harfbuzz::harfbuzz AND NOT WIN32)
  if(APPLE)
    set(ff_cxx_runtime c++)
  else()
    set(ff_cxx_runtime stdc++)
  endif()
  set_property(TARGET harfbuzz::harfbuzz APPEND PROPERTY INTERFACE_LINK_LIBRARIES "${ff_cxx_runtime}")
endif()

# aom and x265 install headers/libraries without a CMake package configuration.
foreach(lib aom x265)
  if(lib STREQUAL "x265" AND NOT FF_EXTERNAL_GPL)
    continue()
  endif()
  set(header "${lib}.h")
  if(lib STREQUAL "aom")
    set(header aom/aom_codec.h)
  endif()
  set(required "")
  if(lib IN_LIST FF_REQUIRED_PACKAGES)
    set(required REQUIRED)
  endif()
  find_path(FF_${lib}_INCLUDE_DIR "${header}" ${required})
  find_library(FF_${lib}_LIBRARY NAMES ${lib} lib${lib} ${lib}-static ${required})
  if(FF_${lib}_INCLUDE_DIR AND FF_${lib}_LIBRARY AND NOT TARGET FFmpegExternal::${lib})
    add_library(FFmpegExternal::${lib} UNKNOWN IMPORTED)
    set_target_properties(FFmpegExternal::${lib} PROPERTIES
      IMPORTED_LOCATION "${FF_${lib}_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${FF_${lib}_INCLUDE_DIR}")
    if(NOT WIN32)
      find_package(Threads REQUIRED)
      set_property(TARGET FFmpegExternal::${lib} PROPERTY INTERFACE_LINK_LIBRARIES "Threads::Threads;m;${CMAKE_DL_LIBS}")
      if(lib STREQUAL "x265")
        if(APPLE)
          set(runtime c++)
        else()
          set(runtime stdc++)
        endif()
        set_property(TARGET FFmpegExternal::${lib} APPEND PROPERTY INTERFACE_LINK_LIBRARIES "${runtime}")
      endif()
    endif()
  endif()
endforeach()

# Explicit pkg-config integration for libraries supplied by the user/package
# manager. These libraries are not downloaded or built by our CMake recipes.
if(FF_EXTERNAL_PKGCONFIG)
  find_package(PkgConfig REQUIRED)
  foreach(pair "libdav1d|dav1d>=1.0.0" "libvpx|vpx>=1.4.0" "libx264|x264" "libass|libass>=0.11.0"
      "libmp3lame|lame" "libfdk_aac|fdk-aac" "libsvtav1|SvtAv1Enc>=0.9.0"
      "libopus|opus" "libvorbis|vorbis" "libvorbisenc|vorbisenc" "libwebp|libwebp"
      "libwebpmux|libwebpmux" "libfreetype|freetype2" "libharfbuzz|harfbuzz")
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 name)
    list(GET pair 1 module)
    if(name IN_LIST FF_EXTERNAL_PKGCONFIG)
      pkg_check_modules(FF_PKG_${name} REQUIRED IMPORTED_TARGET GLOBAL "${module}")
    endif()
  endforeach()
endif()
