# Persist boolean platform results, never paths or an entire CMakeCache.txt.
# Normal CMake checks do not invalidate their result when the test code changes.
set(ff_toolchain_context "${CMAKE_VERSION};${CMAKE_GENERATOR};${CMAKE_GENERATOR_PLATFORM}")
foreach(var CMAKE_SYSTEM_NAME CMAKE_SYSTEM_VERSION CMAKE_SYSTEM_PROCESSOR CMAKE_SIZEOF_VOID_P
    CMAKE_SYSROOT CMAKE_OSX_SYSROOT CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET
    CMAKE_C_STANDARD CMAKE_C_EXTENSIONS CMAKE_MSVC_RUNTIME_LIBRARY CMAKE_BUILD_TYPE
    CMAKE_EXE_LINKER_FLAGS CMAKE_TRY_COMPILE_TARGET_TYPE CMAKE_TOOLCHAIN_FILE)
  string(APPEND ff_toolchain_context "\n${var}=${${var}}")
endforeach()
foreach(lang C CXX)
  foreach(suffix COMPILER COMPILER_ID COMPILER_VERSION COMPILER_TARGET COMPILER_EXTERNAL_TOOLCHAIN
      FLAGS FLAGS_DEBUG FLAGS_RELEASE FLAGS_RELWITHDEBINFO FLAGS_MINSIZEREL IMPLICIT_INCLUDE_DIRECTORIES IMPLICIT_LINK_DIRECTORIES)
    string(APPEND ff_toolchain_context "\n${lang}_${suffix}=${CMAKE_${lang}_${suffix}}")
  endforeach()
  file(SHA256 "${CMAKE_${lang}_COMPILER}" digest)
  string(APPEND ff_toolchain_context "\n${lang}_binary=${digest}")
endforeach()
foreach(var INCLUDE LIB CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH LIBRARY_PATH SDKROOT DEVELOPER_DIR
    WindowsSDKVersion WindowsSDKLibVersion VCToolsVersion UniversalCRTSdkDir UCRTVersion ImageOS ImageVersion)
  string(APPEND ff_toolchain_context "\n${var}=$ENV{${var}}")
endforeach()
# Package/SDK updates also invalidate results when compiler versions stay equal.
foreach(file "${CMAKE_TOOLCHAIN_FILE}" /var/lib/dpkg/status /System/Library/CoreServices/SystemVersion.plist
    "${CMAKE_OSX_SYSROOT}/SDKSettings.json")
  if(EXISTS "${file}" AND NOT IS_DIRECTORY "${file}")
    file(SHA256 "${file}" digest)
    string(APPEND ff_toolchain_context "\n${file}=${digest}")
  endif()
endforeach()
string(SHA256 FF_TOOLCHAIN_KEY "${ff_toolchain_context}")
set(ff_probe_context "${FF_TOOLCHAIN_KEY};${FFMPEG_ASM};${FFMPEG_PROBE_CACHE_SALT}")
file(GLOB ff_probe_modules "${CMAKE_CURRENT_LIST_DIR}/platform/*.cmake")
list(APPEND ff_probe_modules "${CMAKE_CURRENT_LIST_FILE}" "${CMAKE_CURRENT_LIST_DIR}/Platform.cmake")
foreach(file IN LISTS ff_probe_modules)
  file(SHA256 "${file}" digest)
  string(APPEND ff_probe_context "\n${digest}")
endforeach()
string(SHA256 ff_probe_key "${ff_probe_context}")
set(ff_probe_file "${FFMPEG_PROBE_CACHE_DIR}/${ff_probe_key}.txt")

function(ff_is_platform_result name output)
  set(result FALSE)
  foreach(prefix FF_PROBE_ FF_CHECK_ FF_HEADER_)
    string(FIND "${name}" "${prefix}" position)
    if(position EQUAL 0)
      set(result TRUE)
    endif()
  endforeach()
  if(name STREQUAL "FF_AVCAPTURESESSION")
    set(result TRUE)
  endif()
  set(${output} ${result} PARENT_SCOPE)
endfunction()

if(NOT FF_PLATFORM_CACHE_KEY STREQUAL ff_probe_key)
  get_cmake_property(variables CACHE_VARIABLES)
  foreach(var IN LISTS variables)
    ff_is_platform_result("${var}" is_result)
    if(is_result)
      unset(${var} CACHE)
    endif()
  endforeach()
endif()
set(FF_PLATFORM_CACHE_KEY "${ff_probe_key}" CACHE INTERNAL "Platform check identity" FORCE)
if(FFMPEG_PROBE_CACHE AND EXISTS "${ff_probe_file}")
  file(STRINGS "${ff_probe_file}" results)
  set(count 0)
  foreach(line IN LISTS results)
    string(REPLACE "=" ";" pair "${line}")
    list(LENGTH pair length)
    if(NOT length EQUAL 2)
      continue()
    endif()
    list(GET pair 0 name)
    list(GET pair 1 bit)
    ff_is_platform_result("${name}" is_result)
    if(is_result AND (bit STREQUAL "0" OR bit STREQUAL "1"))
      set(${name} "${bit}" CACHE INTERNAL "Cached platform check" FORCE)
      math(EXPR count "${count} + 1")
    endif()
  endforeach()
  message(STATUS "Platform check cache: restored ${count} results (${ff_probe_key})")
else()
  message(STATUS "Platform check cache: ${ff_probe_key} (cold)")
endif()

function(ff_save_platform_cache)
  if(NOT FFMPEG_PROBE_CACHE)
    return()
  endif()
  get_cmake_property(variables CACHE_VARIABLES)
  list(SORT variables)
  set(results "")
  foreach(var IN LISTS variables)
    ff_is_platform_result("${var}" is_result)
    if(is_result)
      if(${var})
        set(bit 1)
      else()
        set(bit 0)
      endif()
      string(APPEND results "${var}=${bit}\n")
    endif()
  endforeach()
  file(MAKE_DIRECTORY "${FFMPEG_PROBE_CACHE_DIR}")
  string(RANDOM LENGTH 12 token)
  file(WRITE "${ff_probe_file}.${token}.tmp" "${results}")
  file(RENAME "${ff_probe_file}.${token}.tmp" "${ff_probe_file}")
endfunction()
