get_filename_component(FFMPEG_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(FFMPEG_SOURCE_DIR "${FFMPEG_ROOT}/ffmpeg" CACHE PATH "FFmpeg source checkout")
set(FFMPEG_PROFILE full CACHE STRING "Component profile: full, minimal, playback, transcode")
set_property(CACHE FFMPEG_PROFILE PROPERTY STRINGS full minimal playback transcode)
option(BUILD_SHARED_LIBS "Build shared FFmpeg libraries" OFF)
option(FFMPEG_GPL "Enable GPL components (same license switch as upstream)" OFF)
option(FFMPEG_VERSION3 "Enable version 3 license components" OFF)
option(FFMPEG_PROGRAMS "Build ffmpeg and ffprobe; ffplay when SDL2 is found" ON)
option(FFMPEG_NETWORK "Enable networking" ON)
option(FFMPEG_SMALL "Optimize for size and omit optional descriptive strings" OFF)
option(FFMPEG_LTO "Enable interprocedural/link time optimization" OFF)
option(FFMPEG_CACHE "Use sccache when available" ON)
option(FFMPEG_PROBE_CACHE "Reuse compatible platform checks across build directories" ON)
set(FFMPEG_PROBE_CACHE_DIR "${FFMPEG_ROOT}/.cache/probes" CACHE PATH "Platform check cache directory")
set(FFMPEG_PROBE_CACHE_SALT "" CACHE STRING "Additional SDK/toolchain cache identity; change after custom SDK/header updates")
set(FFMPEG_DEPENDENCIES "" CACHE STRING "Build external libraries: media, all, or semicolon-separated names")
set(FFMPEG_DEPENDENCY_PREFIX "" CACHE PATH "Use a previously built external dependency installation")
set(FFMPEG_PKG_CONFIG_LIBRARIES "" CACHE STRING "Explicit external lib names supplied through pkg-config, e.g. libdav1d;libass")
option(FFMPEG_FETCH_ZLIB "Build pinned zlib when no system zlib is found" ON)
set(FFMPEG_ASM AUTO CACHE STRING "Native assembly optimizations: AUTO, ON, OFF")
set_property(CACHE FFMPEG_ASM PROPERTY STRINGS AUTO ON OFF)
set(ff_asm_values AUTO ON OFF)
if(NOT FFMPEG_ASM IN_LIST ff_asm_values)
  message(FATAL_ERROR "FFMPEG_ASM must be AUTO, ON, or OFF")
endif()
set(FFMPEG_COMPILE_JOBS "" CACHE STRING "Ninja compile pool size; empty uses Ninja default")
set(FFMPEG_LINK_JOBS 2 CACHE STRING "Ninja link pool size")
set(FFMPEG_DISABLE "" CACHE STRING "Hard-disabled components, e.g. h264_decoder;http_protocol")
foreach(kind DECODERS ENCODERS DEMUXERS MUXERS PARSERS BSFS FILTERS PROTOCOLS INDEVS OUTDEVS HWACCELS)
  set(FFMPEG_${kind} AUTO CACHE STRING "AUTO uses profile, NONE disables group, otherwise a semicolon-separated allowlist")
endforeach()
foreach(lib AVUTIL AVCODEC AVFORMAT AVFILTER AVDEVICE SWSCALE SWRESAMPLE)
  option(FFMPEG_${lib} "Build lib${lib}" ON)
endforeach()
