include(CheckIncludeFile)
include(CheckSymbolExists)
include(CheckCSourceCompiles)
include(TestBigEndian)
set(FF_FACTS "")
function(ff_fact name value)
  if(value)
    set(bit 1)
  else()
    set(bit 0)
  endif()
  set(FF_FACTS "${FF_FACTS}${name}=${bit}\n" PARENT_SCOPE)
  set(${name} ${bit} PARENT_SCOPE)
endfunction()
function(ff_probe name code)
  string(TOUPPER "FF_PROBE_${name}" key)
  check_c_source_compiles("${code}" ${key})
  ff_fact("${name}" "${${key}}")
  set(FF_FACTS "${FF_FACTS}" PARENT_SCOPE)
  set(${name} "${${name}}" PARENT_SCOPE)
endfunction()
function(ff_symbol symbol headers)
  string(TOUPPER "HAVE_${symbol}" name)
  check_symbol_exists("${symbol}" "${headers}" FF_CHECK_${name})
  ff_fact("${name}" "${FF_CHECK_${name}}")
  set(FF_FACTS "${FF_FACTS}" PARENT_SCOPE)
endfunction()

if(MSVC)
  set(CMAKE_REQUIRED_DEFINITIONS -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_WIN32_WINNT=0x0A00 -DWIN32_LEAN_AND_MEAN -DNOMINMAX)
else()
  set(CMAKE_REQUIRED_DEFINITIONS -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L)
endif()
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" cpu)
set(ff_x86_names amd64 x86_64 x64)
set(ff_arm_names aarch64 arm64)
if(cpu IN_LIST ff_x86_names AND CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(FF_ARCH x86)
  ff_fact(ARCH_X86 1)
  ff_fact(ARCH_X86_64 1)
  ff_fact(HAVE_FAST_64BIT 1)
  ff_fact(HAVE_FAST_CLZ 1)
  ff_fact(HAVE_FAST_CMOV 1)
  ff_fact(HAVE_ALIGNED_STACK 1)
  ff_fact(HAVE_FAST_UNALIGNED 1)
  ff_fact(HAVE_I686 1)
elseif(cpu IN_LIST ff_arm_names)
  set(FF_ARCH aarch64)
  ff_fact(ARCH_AARCH64 1)
  ff_fact(HAVE_FAST_64BIT 1)
  ff_fact(HAVE_FAST_CLZ 1)
  ff_fact(HAVE_ALIGNED_STACK 1)
  ff_fact(HAVE_FAST_UNALIGNED 1)
else()
  message(FATAL_ERROR "This native port currently supports x86-64 and ARM64 targets; got ${CMAKE_SYSTEM_PROCESSOR}")
endif()
test_big_endian(FF_BIG_ENDIAN)
ff_fact(HAVE_BIGENDIAN "${FF_BIG_ENDIAN}")
ff_fact(HAVE_PRAGMA_DEPRECATED 1)
ff_fact(CONFIG_RUNTIME_CPUDETECT 1)
ff_fact(CONFIG_SAFE_BITSTREAM_READER 1)
ff_fact(CONFIG_SWSCALE_ALPHA 1)
ff_fact(CONFIG_AUTODETECT 1)
ff_fact(CONFIG_STATIC 1)
if(BUILD_SHARED_LIBS)
  ff_fact(CONFIG_STATIC 0)
endif()
ff_fact(CONFIG_SHARED "${BUILD_SHARED_LIBS}")
ff_fact(CONFIG_PIC 1)
ff_fact(CONFIG_NETWORK "${FFMPEG_NETWORK}")
ff_fact(CONFIG_GPL "${FFMPEG_GPL}")
ff_fact(lgpl_gpl "${FFMPEG_GPL}")
ff_fact(CONFIG_VERSION3 "${FFMPEG_VERSION3}")
if(FFMPEG_GPL AND FFMPEG_VERSION3)
  ff_fact(CONFIG_GPLV3 1)
endif()
if(FFMPEG_VERSION3 AND NOT FFMPEG_GPL)
  ff_fact(CONFIG_LGPLV3 1)
endif()
ff_fact(CONFIG_SMALL "${FFMPEG_SMALL}")
ff_fact(CONFIG_UNSTABLE 1)
ff_fact(optimizations 1)
foreach(lib AVUTIL AVCODEC AVFORMAT AVFILTER AVDEVICE SWSCALE SWRESAMPLE)
  ff_fact(CONFIG_${lib} "${FFMPEG_${lib}}")
endforeach()

if(WIN32)
  include(${CMAKE_CURRENT_LIST_DIR}/platform/Windows.cmake)
else()
  include(${CMAKE_CURRENT_LIST_DIR}/platform/Posix.cmake)
endif()
ff_fact(HAVE_BCRYPT "${bcrypt}")
ff_fact(cxx17 1)
ff_symbol(getenv "stdlib.h")
ff_symbol(strerror_r "string.h")
ff_probe(HAVE_SOCKLEN_T "${net_headers}\nint main(void) { return sizeof(socklen_t) == 0; }")
foreach(type addrinfo group_source_req ip_mreq_source ipv6_mreq pollfd sockaddr_in6 sockaddr_storage)
  string(TOUPPER "${type}" key)
  ff_probe(HAVE_STRUCT_${key} "${net_headers}\nint main(void) { return sizeof(struct ${type}) == 0; }")
endforeach()
ff_probe(HAVE_STRUCT_SOCKADDR_SA_LEN "${net_headers}\nint main(void) { struct sockaddr s; return sizeof(s.sa_len) == 0; }")
ff_probe(HAVE_STRUCT_MSGHDR_MSG_FLAGS "${net_headers}\nint main(void) { struct msghdr s; return sizeof(s.msg_flags) == 0; }")
ff_probe(HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC "#include <sys/stat.h>\nint main(void) { struct stat s; return sizeof(s.st_mtim.tv_nsec) == 0; }")
ff_probe(HAVE_STRUCT_RUSAGE_RU_MAXRSS "#include <sys/resource.h>\nint main(void) { struct rusage s; return sizeof(s.ru_maxrss) == 0; }")
ff_probe(stdatomic "#include <stdatomic.h>\nint main(void) { atomic_int x = 0; return atomic_fetch_add(&x, 1); }")
ff_probe(stdbit "#include <stdbit.h>\nint main(void) { return stdc_count_ones(3u) != 2; }")
ff_probe(HAVE_INT128 "volatile __int128 a = 1; volatile __int128 b = 2;\nint main(void) { return (int)(a / b + a % b); }")
ff_probe(HAVE_INTRINSICS_SSE2 "#include <emmintrin.h>\nint main(void) { __m128i v = _mm_setzero_si128(); return _mm_cvtsi128_si32(v); }")
ff_probe(HAVE_MM_EMPTY "#include <mmintrin.h>\nint main(void) { _mm_empty(); return 0; }")
include(${CMAKE_CURRENT_LIST_DIR}/platform/Assembly.cmake)
set(CMAKE_REQUIRED_LIBRARIES "")
